name: Deploy to AWS

on:
   push:
      branches:
         - production

env:
   AWS_REGION: us-west-1
   AWS_ACCOUNT_ID: 630656099092

jobs:
   deploy:
      name: Deploy to AWS
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Set up Go
           uses: actions/setup-go@v5
           with:
              go-version: "1.23"
              cache: true

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

         - name: Install AWS CDK
           run: npm install -g aws-cdk

         - name: Verify AWS credentials
           run: aws sts get-caller-identity

         - name: Download Go dependencies
           run: go mod download

         - name: CDK Bootstrap (if needed)
           run: cdk bootstrap aws://${{ env.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}

         - name: CDK Synthesize
           run: cdk synth

         - name: CDK Deploy
           run: cdk deploy --require-approval never
